# Site settings
title: Hossein Karami | حسین کرمی
email: hi@hosseinkarami.com
description: توسعه‌دهنده رابط کاربری
baseurl: "http://localhost:3000/"
url: "http://localhost:3000"
twitter: _Karamii
github:  HosseinKarami
behance: HosseinKarami
# Build settings
markdown: kramdown
permalink: pretty
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page:num/"
exclude: ["node_modules", "gulpfile.js", "package.json"]